name: Bug report
description: Report a bug in the Tidepool TypeScript client
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      description: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the issue.
  - type: textarea
    attributes:
      label: Environment
      description: Node version, OS, and any other relevant details.
